apiVersion: v1
kind: Pod
metadata:
  name: git-clone-app
spec:
  initContainers:
  - name: git-clone
    image: alpine/git:latest
    args:
    - clone
    - --single-branch
    - --depth=1
    - --
    - https://github.com/kubernetes/website
    - /data
    volumeMounts:
    - name: git-data
      mountPath: /data
  - name: prepare-config
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Preparing configuration..."
      echo "app.mode=production" > /data/config.properties
      echo "app.port=8080" >> /data/config.properties
      cat /data/config.properties
    volumeMounts:
    - name: git-data
      mountPath: /data
  containers:
  - name: app
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: git-data
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: git-data
    emptyDir: {}
