apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-quota
  namespace: quota-demo
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
