apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing
  name: myapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue
status:
  loadBalancer: {}
